spring:
  application:
    name: zuul
    rabbitmq: 
     host: 192.168.66.131
     port: 5672
     username: admin
     password: admin
    
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
      
      
#zuul:
# routes:
#   item-service: /item-service/**
#   user-service: /user-service/**
#   order-service: /order-service/**


zuul:
  retryable: true
  sensitive-headers:

  
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
  
  
#zuul+hystrix 熔断 测试降级  
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            

#zuul+hystrix dashboard 监控  暴露监控端点
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix-stream
            
            
            
            

            